# Generated by Django 3.0.6 on 2020-05-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='null', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
